In [2]:
import pandas as pd
import numpy as np


import Data

In [6]:
data=pd.read_excel('C:/Users\MEHRANG\Desktop\Data science by Mis rabti\data\DataDemand.xlsx')
data

ضخامت   عرض  كيفيت  جنس ورق   پوشش  وضعيت سفارش  مقدار سفارش  \
0     0.70  1090    3.0      NaN    NaN            0       100000   
1     0.80   800    3.0      NaN    NaN            0       200000   
2     0.70  1305    3.0      NaN    NaN            0       400000   
3     0.70  1305    3.0      NaN    NaN            0       400000   
4     1.00  1290    3.0    542.0  140.0            0       120000   
..     ...   ...    ...      ...    ...          ...          ...   
372   1.00   940    NaN    542.0  140.0            1       100000   
373   0.68  1255    NaN      NaN    NaN            1       200000   
374   0.68  1305    NaN      NaN    NaN            1       200000   
375   0.68  1580    NaN      NaN    NaN            1       100000   
376   0.68  1135    3.0      NaN    NaN            1       150000   

     مقدار عرضه براي توليد  مقدار در سيکل توليد  مقدار آماده به حمل  کد تخليه  \
0                   111000                    0                   0        43   
1                   222000                    0                   0        43   
2                   444000                    0                   0        43   
3                   444000                    0                   0        43   
4                   133200                    0                   0        45   
..                     ...                  ...                 ...       ...   
372                 109000                    0                   0        45   
373                 218000                    0               74568        43   
374                 218000                    0               56681        43   
375                 109000                    0                   0        43   
376                 163500                    0                   0        43   

     مقدار حمل شده  درصد حمل شده به کل سفارش  
0            97280                        97  
1           200740                       100  
2           403080                       101  
3           439140                       110  
4           112900                        94  
..             ...                       ...  
372              0                         0  
373          15580                         8  
374         131160                        66  
375              0                         0  
376          82900                        55  

[377 rows x 13 columns]

In [7]:

data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ضخامت                     377 non-null    float64
 1   عرض                       377 non-null    int64  
 2   كيفيت                     259 non-null    float64
 3   جنس ورق                   310 non-null    float64
 4   پوشش                      310 non-null    float64
 5   وضعيت سفارش               377 non-null    int64  
 6   مقدار سفارش               377 non-null    int64  
 7   مقدار عرضه براي توليد     377 non-null    int64  
 8   مقدار در سيکل توليد       377 non-null    int64  
 9   مقدار آماده به حمل        377 non-null    int64  
 10  کد تخليه                  377 non-null    int64  
 11  مقدار حمل شده             377 non-null    int64  
 12  درصد حمل شده به کل سفارش  377 non-null    int64  
dtypes: float64(4), int64(9)
memory usage: 38.4 KB


chek null attribut

In [8]:
data.isnull().sum()

ضخامت                         0
عرض                           0
كيفيت                       118
جنس ورق                      67
پوشش                         67
وضعيت سفارش                   0
مقدار سفارش                   0
مقدار عرضه براي توليد         0
مقدار در سيکل توليد           0
مقدار آماده به حمل            0
کد تخليه                      0
مقدار حمل شده                 0
درصد حمل شده به کل سفارش      0
dtype: int64

Remove the attribut ehich have 118 null as 259

In [9]:
data_c2=data.drop('كيفيت',axis=1)
data_c2

ضخامت   عرض  جنس ورق   پوشش  وضعيت سفارش  مقدار سفارش  \
0     0.70  1090      NaN    NaN            0       100000   
1     0.80   800      NaN    NaN            0       200000   
2     0.70  1305      NaN    NaN            0       400000   
3     0.70  1305      NaN    NaN            0       400000   
4     1.00  1290    542.0  140.0            0       120000   
..     ...   ...      ...    ...          ...          ...   
372   1.00   940    542.0  140.0            1       100000   
373   0.68  1255      NaN    NaN            1       200000   
374   0.68  1305      NaN    NaN            1       200000   
375   0.68  1580      NaN    NaN            1       100000   
376   0.68  1135      NaN    NaN            1       150000   

     مقدار عرضه براي توليد  مقدار در سيکل توليد  مقدار آماده به حمل  کد تخليه  \
0                   111000                    0                   0        43   
1                   222000                    0                   0        43   
2                   444000                    0                   0        43   
3                   444000                    0                   0        43   
4                   133200                    0                   0        45   
..                     ...                  ...                 ...       ...   
372                 109000                    0                   0        45   
373                 218000                    0               74568        43   
374                 218000                    0               56681        43   
375                 109000                    0                   0        43   
376                 163500                    0                   0        43   

     مقدار حمل شده  درصد حمل شده به کل سفارش  
0            97280                        97  
1           200740                       100  
2           403080                       101  
3           439140                       110  
4           112900                        94  
..             ...                       ...  
372              0                         0  
373          15580                         8  
374         131160                        66  
375              0                         0  
376          82900                        55  

[377 rows x 12 columns]

Replace null with mean fanction


In [12]:
data_c3=data_c2.fillna(data_c2.mean(axis=0))
data_c3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ضخامت                     377 non-null    float64
 1   عرض                       377 non-null    int64  
 2   جنس ورق                   377 non-null    float64
 3   پوشش                      377 non-null    float64
 4   وضعيت سفارش               377 non-null    int64  
 5   مقدار سفارش               377 non-null    int64  
 6   مقدار عرضه براي توليد     377 non-null    int64  
 7   مقدار در سيکل توليد       377 non-null    int64  
 8   مقدار آماده به حمل        377 non-null    int64  
 9   کد تخليه                  377 non-null    int64  
 10  مقدار حمل شده             377 non-null    int64  
 11  درصد حمل شده به کل سفارش  377 non-null    int64  
dtypes: float64(3), int64(9)
memory usage: 35.5 KB


change int and float to str 


In [14]:
li=['پوشش','وضعيت سفارش','کد تخليه','جنس ورق']
data_c3[li]=data_c3[li].astype(str)
data_c3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ضخامت                     377 non-null    float64
 1   عرض                       377 non-null    int64  
 2   جنس ورق                   377 non-null    object 
 3   پوشش                      377 non-null    object 
 4   وضعيت سفارش               377 non-null    object 
 5   مقدار سفارش               377 non-null    int64  
 6   مقدار عرضه براي توليد     377 non-null    int64  
 7   مقدار در سيکل توليد       377 non-null    int64  
 8   مقدار آماده به حمل        377 non-null    int64  
 9   کد تخليه                  377 non-null    object 
 10  مقدار حمل شده             377 non-null    int64  
 11  درصد حمل شده به کل سفارش  377 non-null    int64  
dtypes: float64(1), int64(7), object(4)
memory usage: 35.5+ KB


split input and output


In [15]:
x=data_c3.drop('مقدار سفارش',axis=1)
y=data_c3['مقدار سفارش']
print(x.shape)
print(y.shape)

(377, 11)
(377,)


Validation

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=101)


select Model and learn

In [18]:

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)



LinearRegression()

In [19]:
y_pred=lr.predict(x_test)
y_pred

array([345506.36825404,  99540.31142023, 101022.15893215,  98949.40910244,
       296202.81542632,  99304.36091682, 100508.41282339,  99447.21939431,
        99377.51831425,  99129.65892222,  96229.49607234, 101309.32242944,
       409868.94727303,  99254.73963768, 100539.51439145,  99317.35771867,
       100071.83132512,  96150.27834316,  93011.45190633,  98792.36687802,
       100115.48601086, 122560.38437093,  99984.42150901,  99711.08045487,
        99841.1720518 , 101061.56232573, 252752.51093883,  99417.55290338,
        99996.42308221, 106264.24402726, 101091.18528814,  99060.8605443 ,
        98923.80402299,  98467.26706913,  99874.76040717,  99379.95089574,
        96968.65537591,  93747.48413123, 401728.19391489, 100964.38593399,
       121188.71112093,  98456.75700391, 100126.54484026,  99085.89664824,
       100581.09818824,  99243.26211777,  99363.82761655, 100349.64634033,
       411009.29429243, 202193.33095667, 120625.30320413, 401807.54092723,
       143274.76711325, 1

Evaluation 


In [23]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
mse=mean_squared_error(y_pred,y_test)
mae=mean_absolute_error(y_pred,y_test)
print ('MSE of LinearRegression is :',mse )
print ('RMSE of LinearRegression is :',np.sqrt(mse ))    
print('MAE of LinearRegression is :',mae)

MSE of LinearRegression is : 63539028.01837951
RMSE of LinearRegression is : 7971.137184767272
MAE of LinearRegression is : 3295.2898337412503


 Model DecisinTreeRegration

In [25]:
from sklearn.tree import DecisionTreeRegressor
dr=DecisionTreeRegressor(criterion='mse',max_depth=8,random_state=101)
dr.fit(x_train,y_train)
y_pred=dr.predict(x_test)
mse=mean_squared_error(y_pred,y_test)
mae=mean_absolute_error(y_pred,y_test)
print ('MSE of dr is :',mse )   
print('MAE of dr is :',mae)


MSE of dr is : 65789473.684210524
MAE of dr is : 1789.4736842105262
